name: Test Build Action
on:
  push:
    branches: ["master", "main", "prod", "production"]

jobs:
  TestAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Build Action
        uses: ./
        with:
          name: test-action-build
          preset: linux
          projectDir: test-project
          package: true