name: Test Build Action

on:
  push

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Build Action
        uses: ./
        with:
          name: test-action-build
          preset: linux
          projectDir: test-project
          package: true
          runVerbose: true