name: Test Build Action

on:
  push

jobs:
  test-action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [windows]
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Test Build Action
        id: build
        uses: ./
        with:
          name: test-action-build
          preset: ${{ matrix.platform }}
          projectDir: test-project
          package: true
          runVerbose: true
          isWindows: ${{ matrix.platform == 'windows' }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}